# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary_Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField()),
                ('successes', models.IntegerField()),
                ('last_hit', models.DateTimeField()),
                ('last_success', models.DateTimeField()),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.Dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('translation', models.CharField(max_length=30)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('registered', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='flashcard',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='flashcards.Language'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.User'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='translation_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_language', to='flashcards.Language'),
        ),
        migrations.AddField(
            model_name='dictionary_flashcard',
            name='flashdard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.Flashcard'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.User'),
        ),
    ]
