# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='ABC', max_length=3),
            preserve_default=False,
        ),
    ]
