# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_language_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name_plural': 'Dictionaries'},
        ),
        migrations.AlterModelOptions(
            name='dictionary_flashcard',
            options={'verbose_name_plural': 'Dictionary flashcards'},
        ),
        migrations.RenameField(
            model_name='dictionary_flashcard',
            old_name='flashdard',
            new_name='flashcard',
        ),
    ]
