# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 11:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_auto_20151217_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dictionary_flashcard',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='flashcards.Dictionary'),
        ),
        migrations.AlterField(
            model_name='dictionary_flashcard',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dictionary_flashcard',
            name='last_hit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dictionary_flashcard',
            name='last_success',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dictionary_flashcard',
            name='successes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
